package com.cafeteria.cafeteria_store.data;

import java.io.Serializable;
import java.util.Calendar;

public class Cafeteria implements Serializable{

    /**
     * The id of the order (auto generated by db)
     */
    private int id;

    private String cafeteriaName;

    private String serverIp;

    private String adminEmail;

    private String adminPassword;

    private Calendar openingHoursStart;

    private Calendar openingHoursEnd;

    public int getId() {
        return id;
    }

    public void setId(int id) {
        this.id = id;
    }

    public String getCafeteriaName() {
        return cafeteriaName;
    }

    public void setCafeteriaName(String cafeteriaName) {
        this.cafeteriaName = cafeteriaName;
    }

    public String getServerIp() {
        return serverIp;
    }

    public void setServerIp(String serverIp) {
        this.serverIp = serverIp;
    }

    public String getAdminEmail() {
        return adminEmail;
    }

    public void setAdminEmail(String adminEmail) {
        this.adminEmail = adminEmail;
    }

    public String getAdminPassword() {
        return adminPassword;
    }

    public void setAdminPassword(String adminPassword) {
        this.adminPassword = adminPassword;
    }

    public Calendar getOpeningHoursStart() {
        return openingHoursStart;
    }

    public void setOpeningHoursStart(Calendar openingHoursStart) {
        this.openingHoursStart = openingHoursStart;
    }

    public Calendar getOpeningHoursEnd() {
        return openingHoursEnd;
    }

    public void setOpeningHoursEnd(Calendar openingHoursEnd) {
        this.openingHoursEnd = openingHoursEnd;
    }



}
