package com.cafeteria.cafeteria_store.data;


import java.io.Serializable;

/**
 *
 * @author Shira Elitzur
 *
 * An instance of this class represents Drink item.
 *
 */
public class Drink implements Serializable {

    /**
     * The id of this drink (auto generated by db)
     */
    private int id;

    /**
     * The title of this drink.
     * 1-3 words that describes the drink
     */
    private String title;

    /**
     * The price of this item (only for stand alone item)
     */
    private double price;


    /**
     * Returns the id of this drink
     * @return the id of this drink
     */
    public int getId() {
        return id;
    }

    /**
     * Sets id for this drink
     * @param id
     */
    public void setId(int id) {
        this.id = id;
    }

    /**
     * Returns the title of this drink
     * @return the title of this drink
     */
    public String getTitle() {
        return title;
    }

    /**
     * Sets title to this drink
     * @param title
     */
    public void setTitle(String title) {
        this.title = title;
    }

    /**
     * Returns the price of this drink
     * @return
     */
    public double getPrice() {
        return price;
    }

    /**
     * Sets price for this drink
     * @param price
     */
    public void setPrice(double price) {
        this.price = price;
    }

}
