package com.cafeteria.cafeteria_store.data;

import java.io.Serializable;

/**
 * Created by anael on 14/11/16.
 */

public class Extra  implements Serializable,InventoryItem {
    /**
     * The id of this extra (auto generated by db)
     */
    private int id;

    /**
     * The title of this extra.
     * 1-3 words that describes the extra
     */
    private String title;

    /**
     * The price of this extra.
     */
    private double price;

    private boolean inStock = true;

    /**
     * Returns the id of this extra
     * @return the id of this extra
     */
    public int getId() {
        return id;
    }

    /**
     * Sets id for this extra
     * @param id
     */
    public void setId(int id) {
        this.id = id;
    }

    /**
     * Returns the title of this extra
     * @return the title of this extra
     */
    public String getTitle() {
        return title;
    }

    /**
     * Sets title to this extra
     * @param title
     */
    public void setTitle(String title) {
        this.title = title;
    }

    /**
     * Returns the price of this extra
     * @return the price of this extra
     */
    public double getPrice() {
        return price;
    }

    /**
     * Sets price to this extra
     * @param price
     */
    public void setPrice(double price) {
        this.price = price;
    }

    public boolean isInStock() {
        return inStock;
    }

    public void setInStock(boolean inStock) {
        this.inStock = inStock;
    }
}