package com.cafeteria.cafeteria_store.data;

import android.util.Log;

import java.io.Serializable;

/**
 * Created by anael on 14/11/16.
 */

public class Item implements Serializable,InventoryItem {

    /**
     * The id of this item (auto generated by db)
     */
    private int id;

    /**
     * The title of this item.
     * 1-3 words that describes the item
     */
    private String title;


    /**
     * The price of this item (only for stand alone item)
     */
    private double price;

    private boolean inStock;


    /**
     * Returns the id of this item
     *
     * @return the id of this item
     */
    public int getId() {
        return id;
    }

    /**
     * Sets id for this item
     *
     * @param id
     */
    public void setId(int id) {
        this.id = id;
    }

    /**
     * Returns the title of this item
     *
     * @return the title of this item
     */
    public String getTitle() {
        return title;
    }

    /**
     * Sets title to this item
     *
     * @param title
     */
    public void setTitle(String title) {
        this.title = title;
    }

    /**
     * Returns the price of this item
     *
     * @return
     */
    public double getPrice() {
        return price;
    }

    /**
     * Sets price for this item
     *
     * @param price
     */
    public void setPrice(double price) {
        this.price = price;
    }

    public boolean isInStock() {
        return inStock;
    }

    public void setInStock(boolean inStock) {
        this.inStock = inStock;
    }
}
