package com.cafeteria.cafeteria_store.data;

import java.io.Serializable;
import java.util.Date;
import java.util.List;


/**
 *
 * @author Shira Elitzur
 *
 * An instance of this class represent an order from the cafeteria
 */
public class Order implements Serializable{

    /**
     * The id of the order (auto generated by db)
     */
    private int id;

    /**
     * The customer who made this order
     */
    private Customer customer;

    /**
     * The meals that this order contains
     */
    private List<OrderedMeal> meals;

    /**
     * The items that this order contains
     */
    private List<OrderedItem> items;

    /**
     * The date and time when this order created
     */
    private Date date;

    /**
     * The amount to pay for the items/meals in this order
     */
    private double payment;

    /**
     * An indicator if the order was delivered
     */
    private boolean isDelivered;

    /**
     * An indicator if the order is ready
     */
    private boolean isReady;

    /**
     * The customer can attach a comment to his order
     */
    private String comment;

    /**
     * The customer can add a time for picking up his order
     */
    private String pickupTime;

    /**
     * Returns the id of this order
     * @return the id of this order
     */
    public int getId() {
        return id;
    }

    /**
     * Sets id for this order
     * @param id
     */
    public void setId(int id) {
        this.id = id;
    }

    /**
     * Returns the customer that made this order
     * @return the customer that made this order
     */
    public Customer getCustomer() {
        return customer;
    }

    /**
     * Sets customer object to this order
     * @param customer
     */
    public void setCustomer(Customer customer) {
        this.customer = customer;
    }

    /**
     * Returns the meals that this order contains
     * @return the meals that this order contains
     */
    public List<OrderedMeal> getMeals() {
        return meals;
    }

    /**
     * Sets list of meals for this order
     * @param meals
     */
    public void setMeals(List<OrderedMeal> meals) {
        this.meals = meals;
    }

    /**
     * Returns the items that this order contains
     * @return the items that this order contains
     */
    public List<OrderedItem> getItems() {
        return items;
    }

    /**
     * Sets list of items for this order
     * @param items
     */
    public void setItems(List<OrderedItem> items) {
        this.items = items;
    }

    /**
     * Returns the Date&Time when this order was created
     * @return
     */
    public Date getDate() {
        return date;
    }

    /**
     * Sets the Date and Time for this order ( when it was created )
     * @param
     */
    public void setDate(Date date) {
        this.date = date;
    }

    /**
     * Returns the amount to pay for this order
     * @return the amount to pay for this order
     */
    public double getPayment() {
        payment = 0;
        double drinkPrice = 0;
        double extrasPrice = 0;

        for( OrderedMeal meal : getMeals() ) {
//            if (meal.getChosenDrink()!= null) {
//                drinkPrice = meal.getChosenDrink().getPrice();
//            }
//            // if the amount of extras chosen is bigger then the amount allowed,
//            // add the price of last meal - to be changed according to the expensive/cheap extra
//            if (meal.getChosenExtras().size() > meal.getParentMeal().getExtraAmount()){
//                extrasPrice = meal.getChosenExtras().get(meal.getChosenExtras().size()-1).getPrice();
//            }
//            payment += (meal.getParentMeal().getPrice()) + drinkPrice + extrasPrice;
            payment += meal.getTotalPrice();
        }

        for( OrderedItem item : getItems() ) {
            payment += item.getParentItem().getPrice();
        }

        return payment;
    }

    /**
     * Sets the amount to pay for this order
     * @param payment
     */
    public void setPayment(double payment) {
        this.payment = payment;
    }

    /**
     * Returns true if the order was already delivered or false if not
     * @return true if the order was already delivered
     */
    public boolean isDelivered() {
        return isDelivered;
    }

    /**
     * Sets whether order was already delivered or false if not
     * @param isDelivered
     */
    public void setDelivered(boolean isDelivered) {
        this.isDelivered = isDelivered;
    }

    /**
     * Returns true if the order is ready or false if it is not yet ready
     * @return
     */
    public boolean isReady() {
        return isReady;
    }

    /**
     * Sets whether the order is ready
     * @param isReady
     */
    public void setReady(boolean isReady) {
        this.isReady = isReady;
    }

    /**
     * Returns the comment that was attached to this order
     * @return the comment of this order
     */
    public String getComment() {
        return comment;
    }

    /**
     * Sets comment to this order
     * @param comment
     */
    public void setComment(String comment) {
        this.comment = comment;
    }

    public String getPickupTime() {
        return pickupTime;
    }

    public void setPickupTime(String pickupTime) {
        this.pickupTime = pickupTime;
    }


}
