package com.cafeteria.cafeteria_store.data;

import java.io.Serializable;

/**
 * Created by ashom on 15-Nov-16.
 */

public class ServingForm  implements Serializable,InventoryItem {
    /**
     * The id of this main item (auto generated by db)
     */
    private int id;

    private String title;

    private boolean inStock;

    public int getId() {
        return id;
    }


    public void setId(int id) {
        this.id = id;
    }

    public String getTitle() {
        return title;
    }


    public void setTitle(String title) {
        this.title = title;
    }

    public boolean isInStock() {
        return inStock;
    }

    @Override
    public void setPrice(double price) {

    }


    @Override
    public double getPrice() {
        return 0;
    }

    public void setInStock(boolean inStock) {
        this.inStock = inStock;
    }

}
